#!/bin/sh
#
# @name 1DOF Tilt-Quadrotor
#
# @url
#
# @type Tilt-Quad
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Pitch servo motor for rotor 1 & 2 arm
# @output AUX2 Pitch servo motor for rotor 3 & 4 arm
#
# @maintainer Krunal Chaudhari <krunal2103@gmail.com>
#

sh /etc/init.d/rc.mc_defaults


# Configure this as Quadrotor
set MAV_TYPE 2

# Set mixer
set MIXER tilt_quad_x_1dof
set MIXER_AUX tilt_quad_x_1dof

set PWM_OUT 1234
